# Generated by Django 3.2.3 on 2021-09-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar este cargo, deshabilite esta casilla.')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('status', models.BooleanField(default=True, help_text='Para desactivar este departamento, deshabilite esta casilla.')),
            ],
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nombre',
            new_name='razon_social',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(default='Arauco', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut',
            field=models.CharField(default='76503688-1', error_messages={'unique': 'Ya existe un cliente con este RUT registrado.'}, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rut_representante',
            field=models.CharField(default='18321654-6', error_messages={'unique': 'Ya existe un cliente con este RUT registrado.'}, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.ciudad'),
        ),
        migrations.AddField(
            model_name='planta',
            name='direccion_comercial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.provincia'),
        ),
        migrations.AddField(
            model_name='planta',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.region'),
        ),
    ]
