# Generated by Django 3.2.3 on 2021-09-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_auto_20210920_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='rut_representante',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
