# Generated by Django 3.2.3 on 2021-09-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_auto_20210913_1124'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cliente',
        ),
        migrations.AddField(
            model_name='user',
            name='cliente',
            field=models.ManyToManyField(help_text='Seleccione solo un cliente si el perfil que esta seleccionado es Trabajador.', to='utils.Cliente'),
        ),
    ]
