# Generated by Django 3.2.3 on 2021-09-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210914_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='codigo',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='código'),
        ),
    ]
