# Generated by Django 3.2.3 on 2021-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_alter_planta_rut_representante'),
        ('contratos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantilla',
            name='cliente',
        ),
        migrations.AddField(
            model_name='plantilla',
            name='clientes',
            field=models.ManyToManyField(to='utils.Cliente'),
        ),
    ]
